/** @format */

module.exports = {
	// ** MANAGE ADMINS ACTIONS
	CREATE_ADMIN: 'CREATE_ADMIN',
	EDIT_ADMIN: 'EDIT_ADMIN',
	DELETE_ADMIN: 'DELETE_ADMIN',

	// ** BLOGS ACTIONS
	CREATE_BLOG_TAG: 'CREATE_BLOG_TAG',
	EDIT_BLOG_TAG: 'EDIT_BLOG_TAG',
	DELETE_BLOG_TAG: 'DELETE_BLOG_TAG',

	CREATE_BLOG_CATEGORY: 'CREATE_BLOG_CATEGORY',
	EDIT_BLOG_CATEGORY: 'EDIT_BLOG_CATEGORY',
	DELETE_BLOG_CATEGORY: 'DELETE_BLOG_CATEGORY',

	CREATE_BLOG: 'CREATE_BLOG',
	EDIT_BLOG: 'EDIT_BLOG',
	DELETE_BLOG: 'DELETE_BLOG',

	CREATE_BLOG_AUTHOR: 'CREATE_BLOG_AUTHOR',
	EDIT_BLOG_AUTHOR: 'EDIT_BLOG_AUTHOR',
	DELETE_BLOG_AUTHOR: 'DELETE_BLOG_AUTHOR',

	UPDATE_BLOG_SETTINGS: 'UPDATE_BLOG_SETTINGS',

	// ** DDAYS OF ORSHIP ACTIONS
	CREATE_DAY_OF_WORSHIP: 'CREATE_DAY_OF_WORSHIP',
	EDIT_DAY_OF_WORSHIP: 'EDIT_DAY_OF_WORSHIP',
	DELETE_DAY_OF_WORSHIP: 'DELETE_BLOG_AUTHOR',

	// ** STATIC PAGE SEO ACTIONS
	UPDATE_PAGE_SEO_DATA: 'UPDATE_PAGE_SEO_DATA',
};
