/** @format */

module.exports = {
	TAGS_DESCRIPTION_CHARACTERS_LIMIT: 200,
	CATEGORIES_DESCRIPTION_CHARACTERS_LIMIT: 70,

	BLOG_SUMMARY_LIMIT: 100,

	WORSHIP_DAY_QUOTE_LIMIT: 100,
	WORSHIP_DAY_DESCRIPTION_LIMIT: 200,

	META_DESCRIPTION_LIMIT: 200,
	META_KEYWORDS_LIMIT: 200,
};
